//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates
    {
        public int CertificateID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
