//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeTr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> InstructorID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Instructors Instructors { get; set; }
    }
}
